Repository gethinode/hinode, pull requests merged in 2023-10, with the labels that each got.

#544 Update Hugo module dependencies
  exampleSite/go.sum
  go.mod
  go.sum
Labels: dependencies

#545 Fix spacing of inline elements
  assets/scss/common/_variables-dart.scss
  exampleSite/data/abbr.yml
  layouts/_default/single.html
  layouts/partials/assets/button.html
  layouts/partials/assets/sharing.html
  layouts/shortcodes/button.html
  layouts/shortcodes/release.html
  layouts/shortcodes/tooltip.html
  netlify.toml
  package-lock.json
  package.json
Labels: bug

#547 Support custom card ratio
  assets/scss/components/_card.scss
  layouts/partials/assets/card-group.html
  layouts/partials/assets/card.html
Labels: enhancement

#548 Consolidate list page and home page
  i18n/en.yaml
  i18n/nl.yaml
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/index.html
Labels: enhancement

#549 Refactor base layout
  assets/scss/common/_styles.scss
  config/_default/params.toml
  content/_index.md
  exampleSite/config/_default/params.toml
  exampleSite/content/en/_index.md
  exampleSite/content/fr/_index.md
  exampleSite/content/nl/_index.md
  exampleSite/hugo_stats.json
  hugo_stats.json
  layouts/_default/baseof.html
  layouts/partials/assets/section-list.html
  layouts/partials/assets/section-menu.html
  layouts/partials/assets/toc-main.html
  layouts/partials/assets/toc.html
  layouts/partials/footer/social.html
  layouts/partials/home/featured.html
  layouts/partials/list/featured.html
Labels: enhancement, breaking-change

#550 Sync with main
  assets/scss/common/_styles.scss
  assets/scss/components/_card.scss
  config/_default/params.toml
  content/_index.md
  exampleSite/config/_default/params.toml
  exampleSite/content/en/_index.md
  exampleSite/content/fr/_index.md
  exampleSite/content/nl/_index.md
  exampleSite/hugo_stats.json
  hugo_stats.json
  i18n/en.yaml
  i18n/nl.yaml
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/assets/card-group.html
  layouts/partials/assets/card.html
  layouts/partials/assets/section-list.html
  layouts/partials/assets/section-menu.html
  layouts/partials/assets/toc-main.html
  layouts/partials/assets/toc.html
  layouts/partials/footer/social.html
  layouts/partials/home/featured.html
  layouts/partials/list/featured.html
  package-lock.json
  package.json
Labels: skip-changelog

#551 Update French Translation with latest hinode version
  exampleSite/content/fr/blog/components.md
Labels: enhancement

#555 Refine base layout
  assets/scss/layouts/_type.scss
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  exampleSite/hugo_stats.json
  hugo_stats.json
  layouts/_default/list.html
  layouts/partials/assets/section-header.html
  layouts/partials/assets/section-list.html
  layouts/partials/list/featured.html
  layouts/shortcodes/card.html
  package-lock.json
  package.json
Labels: bug

#557 Add color mode support for animations
  exampleSite/go.sum
  go.mod
  go.sum
  layouts/_default/list.html
  layouts/partials/list/featured.html
  netlify.toml
  package-lock.json
  package.json
Labels: enhancement

#558 Refine featured partial
  layouts/partials/list/featured.html
Labels: bug

#559 Remove trailing whitespace from external link icon
  layouts/partials/utilities/link.html
Labels: bug

#560 Refine section heading rendering
  layouts/_default/list.html
Labels: bug

#561 Standardize padding
  layouts/tags/list.html
Labels: bug

#562 Update Hugo module dependencies
  exampleSite/go.sum
  go.mod
  go.sum
Labels: dependencies

#563 Add modal search support
  assets/scss/components/_navbar.scss
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  exampleSite/hugo_stats.json
  layouts/partials/assets/navbar.html
  package-lock.json
  package.json
Labels: enhancement

#564 Optimize js and css handling
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  exampleSite/config/postcss.config.js
  exampleSite/content/fr/about.md
  exampleSite/content/nl/about.md
  exampleSite/hugo_stats.json
  hugo_stats.json
  layouts/_default/baseof.html
  layouts/partials/footer/scripts.html
  layouts/partials/head/stylesheet.html
Labels: enhancement

#566 Improve definition of image dimensions
  layouts/partials/assets/image.html
  layouts/partials/assets/navbar.html
  layouts/partials/utilities/GetWidth.html
Labels: enhancement

#567 Refine layout
  assets/scss/app-dart.scss
  assets/scss/app.scss
  assets/scss/components/_abbr.scss
  assets/scss/components/_toc.scss
  exampleSite/hugo_stats.json
  layouts/_default/single.html
  layouts/partials/assets/navbar.html
  layouts/shortcodes/abbr.html
  package-lock.json
  package.json
Labels: bug

#568 Refactor link partial and shortcode
  exampleSite/content/en/blog/bootstrap-elements.md
  exampleSite/content/fr/blog/bootstrap-elements.md
  layouts/_default/single.html
  layouts/partials/utilities/GetPage.html
  layouts/partials/utilities/link.html
  layouts/shortcodes/link.html
  package-lock.json
  package.json
Labels: breaking-change

#569 Use redirect for more button when applicable
  layouts/_default/list.html
Labels: bug

#570 Support content view templates for single pages
  layouts/_default/single.html
  layouts/_default/single/body.html
  layouts/_default/single/footer.html
  layouts/_default/single/header.html
  layouts/docs/single/body.html
  layouts/docs/single/footer.html
  layouts/docs/single/header.html
  layouts/minimal/single/body.html
  layouts/minimal/single/footer.html
  layouts/minimal/single/header.html
  layouts/partials/single/thumbnail.html
Labels: breaking-change

#572 Refine base layout
  assets/scss/common/_styles.scss
  assets/scss/common/_variables-dart.scss
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  exampleSite/hugo_stats.json
  hugo_stats.json
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/partials/assets/section-header.html
  layouts/partials/head/stylesheet.html
  layouts/partials/list/featured.html
  layouts/shortcodes/button.html
  package-lock.json
  package.json
Labels: bug

#571 Update Hugo module dependencies
  exampleSite/go.sum
  go.mod
  go.sum
Labels: dependencies

#573 Fix alignment of 404 message
  exampleSite/hugo_stats.json
  hugo_stats.json
  layouts/404.html
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/tags/list.html
  package-lock.json
  package.json
Labels: bug

#574 Fix section menu initialization
  exampleSite/content/fr/blog/bootstrap-elements.md
  hugo_stats.json
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/partials/utilities/GetSections.html
  package-lock.json
  package.json
Labels: bug

#575 Improve layout
  assets/scss/app-dart.scss
  assets/scss/app.scss
  assets/scss/components/_button.scss
  layouts/partials/assets/button.html
  layouts/partials/assets/navbar.html
  layouts/partials/list/featured.html
  layouts/partials/utilities/GetWidth.html
  package-lock.json
  package.json
Labels: bug

#576 Fix buttons
  assets/scss/components/_button.scss
  go.mod
  go.sum
  i18n/de.yaml
  i18n/en.yaml
  i18n/fr.yaml
  i18n/nl.yaml
  layouts/_default/single.html
  layouts/partials/assets/navbar.html
  layouts/partials/assets/page-alert.html
  layouts/partials/assets/toast.html
  layouts/shortcodes/alert.html
Labels: bug

#577 Update Hugo module dependencies
  exampleSite/go.sum
Labels: dependencies

#578 Improve brand logo accessibility
  layouts/partials/assets/navbar.html
Labels: bug

#579 Fix accessibility of featured thumbnail
  layouts/partials/list/featured.html
Labels: bug

#580 Refactor image partial
  layouts/partials/assets/image.html
Labels: bug

#581 Improve modal search
  exampleSite/go.sum
  exampleSite/hugo_stats.json
  go.mod
  go.sum
  package-lock.json
  package.json
Labels: bug

#584 Fix search background placeholder
  layouts/partials/assets/navbar.html
  package-lock.json
  package.json
Labels: bug

#585 Add support for horizontal navbar
  assets/scss/components/_navbar.scss
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  layouts/partials/assets/navbar.html
Labels: enhancement

#586 Fix positioning of footer in list pages
  layouts/_default/list.html
  layouts/partials/assets/section-list.html
Labels: bug

#587 Support lazy loading of images
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/partials/assets/card-group.html
  layouts/partials/assets/card.html
  layouts/partials/assets/carousel-item.html
  layouts/partials/assets/image.html
  layouts/partials/assets/list.html
  layouts/partials/assets/nav.html
  layouts/partials/assets/persona.html
  layouts/partials/assets/section-list.html
  layouts/partials/utilities/GetSections.html
  layouts/shortcodes/image.html
Labels: enhancement

#588 Fix alignment of featured image in full cover mode
  exampleSite/hugo_stats.json
  layouts/partials/assets/image.html
  layouts/partials/list/featured.html
  layouts/shortcodes/image.html
Labels: bug

#589 Fix thumbnail titles and sidebar toggler positioning
  layouts/partials/assets/list.html
  layouts/partials/assets/navbar.html
  layouts/partials/assets/persona.html
  package-lock.json
  package.json
Labels: bug

#590 Add horizontal navigation styling parameters
  assets/scss/app-dart.scss
  assets/scss/app.scss
  assets/scss/common/_variables-dart.scss
  assets/scss/common/_variables.scss
  assets/scss/components/_navbar.scss
  assets/scss/theme/_variables.scss
  exampleSite/hugo_stats.json
  package-lock.json
  package.json
Labels: enhancement

#591 Fix section title and modal search
  config/postcss.config.js
  exampleSite/config/postcss.config.js
  layouts/partials/utilities/GetSections.html
Labels: bug

#592 Support layout types for list pages
  layouts/_default/list.html
  layouts/_default/list/body.html
  layouts/_default/list/footer.html
  layouts/_default/list/header.html
  layouts/partials/utilities/bundle.html
Labels: enhancement

#593 Bump package release
  package-lock.json
  package.json
Labels: skip-changelog

#594 Sync with main
  layouts/_default/list.html
  layouts/_default/list/body.html
  layouts/_default/list/footer.html
  layouts/_default/list/header.html
  layouts/partials/utilities/bundle.html
  package-lock.json
  package.json
Labels: skip-changelog

#595 Address Hugo v0.120.0 deprecation warnings
  assets/js/analytics.js
  config/_default/hugo.toml
  exampleSite/config/_default/hugo.toml
  layouts/partials/assets/navbar.html
  layouts/partials/footer/scripts.html
  package-lock.json
  package.json
Labels: bug

#596 Make section menu responsive
  assets/scss/components/_toc.scss
  i18n/en.yaml
  i18n/nl.yaml
  layouts/_default/list.html
  layouts/partials/assets/section-menu.html
  layouts/partials/list/featured.html
  layouts/tags/list.html
Labels: bug
