Repository gethinode/hinode, pull requests merged in 2023-12, with the labels that each got.

#651 Sync with main
  i18n/de.yaml
  layouts/partials/assets/card-group.html
  layouts/partials/assets/section-list.html
  layouts/partials/utilities/GetSections.html
  package-lock.json
  package.json
Labels: skip-changelog

#652 Update Netlify build environment
  netlify.toml
  package-lock.json
  package.json
Labels: enhancement

#658 Update Hugo module dependencies
  exampleSite/go.sum
  go.mod
  go.sum
Labels: dependencies

#659 Sync with main
  exampleSite/go.sum
  go.mod
  go.sum
  package-lock.json
  package.json
Labels: skip-changelog

#660 Add support for absolute paths
  config/_default/hugo.toml
  layouts/partials/utilities/GetResource.html
  package-lock.json
  package.json
Labels: enhancement

#661 Update Hugo module dependencies
  exampleSite/go.sum
  go.mod
  go.sum
Labels: dependencies

#664 Add Chinese translation files
  i18n/zh-hans.yaml
  i18n/zh-hant.yaml
Labels: enhancement

#667 Update Hugo module dependencies
  exampleSite/go.sum
  go.mod
  go.sum
Labels: dependencies

#670 Refactor argument validation and documentation
  data/structures/card.yml
  exampleSite/hugo_stats.json
  i18n/en.yaml
  i18n/nl.yaml
  layouts/partials/assets/card.html
  layouts/partials/assets/table.html
  layouts/partials/utilities/GetArgParent.html
  layouts/partials/utilities/IsInvalidArgs.html
  layouts/shortcodes/args.html
  layouts/shortcodes/card.html
  layouts/shortcodes/img.html
  package-lock.json
  package.json
Labels: enhancement

#671 Improve argument validation and documentation
  data/structures/card.yml
  exampleSite/hugo_stats.json
  layouts/partials/assets/button.html
  layouts/partials/utilities/IsInvalidArgs.html
  layouts/shortcodes/args.html
  package-lock.json
  package.json
Labels: enhancement

#672 Refactor abbr and accordion shortcodes
  data/structures/abbr.yml
  data/structures/accordion-item.yml
  data/structures/accordion.yml
  data/structures/card.yml
  exampleSite/hugo_stats.json
  layouts/_default/baseof.html
  layouts/partials/utilities/CastBool.html
  layouts/partials/utilities/IsInvalidArgs.html
  layouts/shortcodes/abbr.html
  layouts/shortcodes/accordion-item.html
  layouts/shortcodes/accordion.html
  layouts/shortcodes/card.html
Labels: enhancement

#673 Refactor alert and args shortcodes
  data/structures/alert.yml
  data/structures/args.yml
  layouts/shortcodes/alert.html
  layouts/shortcodes/args.html
  package-lock.json
  package.json
Labels: enhancement

#674 Refactor badge and card-group
  data/structures/args.yml
  data/structures/badge.yml
  data/structures/card-group.yml
  data/structures/card.yml
  layouts/partials/assets/card-group.html
  layouts/partials/assets/card.html
  layouts/partials/assets/section-list.html
  layouts/partials/utilities/IsInvalidArgs.html
  layouts/shortcodes/args.html
  layouts/shortcodes/badge.html
  layouts/shortcodes/card-group.html
Labels: enhancement

#675 Refactor breadcrumb
  data/structures/breadcrumb.yml
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/partials/assets/breadcrumb.html
  layouts/partials/list/featured.html
  layouts/partials/utilities/IsInvalidArgs.html
  layouts/shortcodes/breadcrumb.html
  layouts/tags/list.html
Labels: breaking-change

#677 Refactor button
  data/structures/button.yml
  layouts/partials/assets/breadcrumb.html
  layouts/partials/assets/button.html
  layouts/shortcodes/button.html
Labels: enhancement

#679 Refactor youtube, tooltip, toast, and timeline shortcodes / partials
  data/structures/button.yml
  data/structures/card.yml
  data/structures/timeline.yml
  data/structures/toast.yml
  data/structures/tooltip.yml
  data/structures/version.yml
  data/structures/youtube.yml
  exampleSite/hugo_stats.json
  layouts/partials/assets/sharing.html
  layouts/partials/assets/toast.html
  layouts/partials/assets/version.html
  layouts/partials/utilities/GetI18nData.html
  layouts/partials/utilities/IsInvalidArgs.html
  layouts/shortcodes/args.html
  layouts/shortcodes/timeline.html
  layouts/shortcodes/toast.html
  layouts/shortcodes/tooltip.html
  layouts/shortcodes/youtube.html
Labels: enhancement

#680 Refactor table shortcode
  data/structures/table.yml
  layouts/shortcodes/table.html
Labels: breaking-change

#681 Refactor sub, sup, spinner, release, persona, navbar, nav, mark, and link
  data/structures/accordion-item.yml
  data/structures/accordion.yml
  data/structures/alert.yml
  data/structures/link.yml
  data/structures/mark.yml
  data/structures/nav-item.yml
  data/structures/nav.yml
  data/structures/navbar.yml
  data/structures/persona.yml
  data/structures/release.yml
  data/structures/spinner.yml
  data/structures/sub.yml
  data/structures/sup.yml
  exampleSite/content/en/blog/bootstrap-elements.md
  layouts/partials/assets/link.html
  layouts/partials/assets/nav-item.html
  layouts/partials/assets/nav.html
  layouts/partials/assets/navbar.html
  layouts/partials/assets/persona.html
  layouts/partials/assets/sidebar.html
  layouts/partials/footer/footer.html
  layouts/partials/single/thumbnail.html
  layouts/partials/utilities/IsInvalidArgs.html
  layouts/partials/utilities/link.html
  layouts/shortcodes/link.html
  layouts/shortcodes/mark.html
  layouts/shortcodes/nav-item.html
  layouts/shortcodes/nav.html
  layouts/shortcodes/navbar.html
  layouts/shortcodes/persona.html
  layouts/shortcodes/release.html
  layouts/shortcodes/spinner.html
  layouts/shortcodes/sub.html
  layouts/shortcodes/sup.html
Labels: enhancement

#682 Refactor image partial and shortcode
  data/structures/image.yml
  layouts/partials/assets/card.html
  layouts/partials/assets/carousel-item.html
  layouts/partials/assets/image.html
  layouts/partials/assets/nav.html
  layouts/partials/assets/persona.html
  layouts/partials/assets/section-header.html
  layouts/partials/list/featured.html
  layouts/partials/single/thumbnail.html
  layouts/partials/utilities/GetIllustration.html
  layouts/shortcodes/image.html
Labels: breaking-change

#683 Refactor remaining shortcodes
  data/structures/abbr.yml
  data/structures/args.yml
  data/structures/button-group.yml
  data/structures/button.yml
  data/structures/card-group.yml
  data/structures/card.yml
  data/structures/carousel-item.yml
  data/structures/carousel.yml
  data/structures/collapse.yml
  data/structures/command.yml
  data/structures/docs.yml
  data/structures/example.yml
  data/structures/file.yml
  data/structures/image.yml
  data/structures/kbd.yml
  data/structures/link.yml
  data/structures/navbar.yml
  data/structures/persona.yml
  data/structures/release.yml
  data/structures/table.yml
  data/structures/toast.yml
  exampleSite/hugo_stats.json
  layouts/partials/assets/carousel-item.html
  layouts/shortcodes/button-group.html
  layouts/shortcodes/carousel.html
  layouts/shortcodes/collapse.html
  layouts/shortcodes/command.html
  layouts/shortcodes/docs.html
  layouts/shortcodes/example.html
  layouts/shortcodes/file.html
  layouts/shortcodes/img.html
  layouts/shortcodes/kbd.html
  layouts/shortcodes/mark.html
  package-lock.json
  package.json
Labels: enhancement

#684 Fix args validation
  data/structures/table.yml
  layouts/partials/assets/card-group.html
  layouts/partials/assets/list.html
  layouts/partials/assets/nav.html
  layouts/partials/assets/navbar.html
  layouts/partials/assets/persona.html
  layouts/shortcodes/accordion.html
  layouts/shortcodes/example.html
  layouts/shortcodes/kbd.html
  layouts/shortcodes/navbar.html
  layouts/shortcodes/table.html
  package-lock.json
  package.json
Labels: bug

#685 Fix args validation
  data/structures/card-group.yml
  data/structures/nav.yml
  layouts/partials/assets/section-list.html
  layouts/partials/utilities/IsInvalidArgs.html
  package-lock.json
  package.json
Labels: bug

#686 Fix purge settings and arg init
  config/postcss.config.js
  exampleSite/config/postcss.config.js
  exampleSite/hugo_stats.json
  layouts/partials/assets/persona.html
  layouts/partials/assets/section-list.html
  package-lock.json
  package.json
Labels: bug

#688 Refine args handling
  data/structures/accordion.yml
  data/structures/badge.yml
  data/structures/button.yml
  data/structures/card-group.yml
  data/structures/card.yml
  data/structures/carousel-item.yml
  data/structures/carousel.yml
  data/structures/command.yml
  data/structures/docs.yml
  data/structures/example.yml
  data/structures/file.yml
  data/structures/image.yml
  data/structures/link.yml
  data/structures/mark.yml
  data/structures/nav-item.yml
  data/structures/nav.yml
  data/structures/navbar.yml
  data/structures/release.yml
  data/structures/spinner.yml
  data/structures/sub.yml
  data/structures/sup.yml
  data/structures/youtube.yml
  exampleSite/hugo_stats.json
  layouts/partials/assets/card-group.html
  layouts/partials/assets/navbar.html
  layouts/partials/assets/section-list.html
  layouts/shortcodes/alert.html
  layouts/shortcodes/args.html
  layouts/shortcodes/button.html
  layouts/shortcodes/card-group.html
  layouts/shortcodes/card.html
  layouts/shortcodes/nav-item.html
  layouts/shortcodes/release.html
  package-lock.json
  package.json
Labels: bug

#689 Move utilities to separate module
  config/_default/hugo.toml
  data/structures/persona.yml
  exampleSite/go.mod
  go.mod
  go.sum
  layouts/partials/utilities/CastBool.html
  layouts/partials/utilities/GetArgParent.html
  layouts/partials/utilities/GetBreakpoint.html
  layouts/partials/utilities/GetDescription.html
  layouts/partials/utilities/GetI18nData.html
  layouts/partials/utilities/GetImage.html
  layouts/partials/utilities/GetMenu.html
  layouts/partials/utilities/GetPage.html
  layouts/partials/utilities/GetResource.html
  layouts/partials/utilities/GetVal.html
  layouts/partials/utilities/GetVersion.html
  layouts/partials/utilities/GetWidth.html
  layouts/partials/utilities/IsInvalidArgs.html
  layouts/partials/utilities/IsOlder.html
  layouts/partials/utilities/ProcessContent.html
  layouts/partials/utilities/URLJoin.html
  layouts/partials/utilities/bundle.html
  layouts/partials/utilities/date.html
  layouts/partials/utilities/git.html
  netlify.toml
  package-lock.json
  package.json
Labels: enhancement
