Repository gethinode/hinode, pull requests merged in 2024-05, with the labels that each got.

#909 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#911 Fix linting issues
  assets/scss/components/_nav.scss
  assets/scss/components/_navbar.scss
Labels: bug

#912 Introduce pagination parameter for card groups
  data/structures/card-group.yml
  exampleSite/hugo_stats.json
  layouts/partials/assets/card-group.html
  package-lock.json
  package.json
Labels: bug

#913 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#915 Improve image set rendering
  data/structures/card.yml
  data/structures/image.yml
  exampleSite/hugo_stats.json
  layouts/partials/assets/card-group.html
  layouts/partials/assets/card.html
  layouts/partials/assets/image.html
  layouts/partials/list/featured.html
  package-lock.json
  package.json
Labels: release-highlight

#917 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#920 Fix card rounding
  assets/scss/components/_card.scss
  exampleSite/hugo_stats.json
  hugo_stats.json
  layouts/partials/assets/card.html
  package-lock.json
  package.json
Labels: bug

#922 Restrict external link validation to http(s) scheme only
  layouts/partials/assets/button.html
  package-lock.json
  package.json
Labels: bug

#924 Update Netlify build environment
  layouts/partials/assets/download.html
  layouts/partials/assets/section-list.html
  layouts/partials/assets/table.html
  layouts/partials/assets/toc-main.html
  netlify.toml
Labels: documentation, dependencies

#925 Refine section menu margins
  layouts/partials/assets/section-menu.html
  package-lock.json
  package.json
Labels: bug

#931 Fix button layout of type link in horizontal stack
  assets/scss/components/_button.scss
  exampleSite/hugo_stats.json
  layouts/partials/assets/button.html
  package-lock.json
  package.json
Labels: bug

#935 Improve handling of links that include the site's base URL
  exampleSite/content/en/blog/bootstrap-elements.md
  layouts/partials/assets/link.html
  layouts/shortcodes/link.html
  package-lock.json
  package.json
Labels: enhancement

#938 Add 'external' param to link shortcut
  data/structures/link.yml
  layouts/partials/assets/link.html
  layouts/shortcodes/link.html
Labels: enhancement

#939 Bump package release
  package-lock.json
  package.json
Labels: skip-changelog

#940 Add support for image CDNs
  config/_default/server.toml
  data/dimensions.yml
  data/structures/image-adapter.yml
  exampleSite/config/_default/server.toml
  exampleSite/content/en/blog/image.md
  exampleSite/hugo_stats.json
  layouts/partials/assets/adapters/cloudinary.html
  layouts/partials/assets/adapters/hugo.html
  layouts/partials/assets/helpers/GetDimension.html
  layouts/partials/assets/helpers/SetPortrait.html
  layouts/partials/assets/helpers/image-definition.html
  layouts/partials/assets/helpers/image-set.html
  layouts/partials/assets/image.html
  netlify.toml
  package-lock.json
  package.json
Labels: release-highlight

#942 Fix conversion of image dimensions
  layouts/partials/assets/helpers/image-definition.html
  package-lock.json
  package.json
Labels: bug

#943 Refine CDN image handling
  data/dimensions.yml
  exampleSite/config/_default/params.toml
  layouts/partials/assets/adapters/cloudinary.html
  layouts/partials/assets/helpers/GetDimension.html
  layouts/partials/assets/helpers/image-definition.html
  package-lock.json
  package.json
Labels: bug

#950 Extend image adapters
  config/_default/params.toml
  config/_default/server.toml
  exampleSite/config/_default/server.toml
  exampleSite/content/en/blog/image.md
  exampleSite/hugo_stats.json
  layouts/partials/assets/adapters/imagekit.html
  layouts/partials/assets/adapters/imgix.html
  layouts/partials/assets/helpers/image-definition.html
  layouts/partials/assets/helpers/image-set.html
  netlify.toml
  package-lock.json
  package.json
Labels: enhancement

#945 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#951 Fix linting issue
  assets/scss/components/_card.scss
Labels: bug

#952 Make module configurations loosely coupled
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  layouts/_default/baseof.html
  layouts/partials/footer/optional-scripts.html
  layouts/partials/footer/scripts.html
  layouts/partials/head/head.html
  layouts/partials/head/stylesheet.html
  layouts/partials/utilities/InitModules.html
Labels: breaking-change, release-highlight

#953 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#954 Use default module configuration
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  layouts/partials/utilities/InitModules.html
  package-lock.json
  package.json
Labels: enhancement

#955 Fix image color mode
  layouts/partials/assets/image.html
  package-lock.json
  package.json
Labels: bug

#956 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#957 Improve image handling
  layouts/partials/assets/helpers/image-definition.html
  package-lock.json
  package.json
Labels: bug

#959 Support plain images
  data/structures/image.yml
  exampleSite/content/en/blog/image.md
  layouts/partials/assets/helpers/image-definition.html
  layouts/partials/assets/image.html
  layouts/shortcodes/image.html
  package-lock.json
  package.json
Labels: enhancement

#960 Use latest resource handling
  go.mod
  go.sum
Labels: enhancement

#961 Prevent processing of plain images
  layouts/partials/assets/helpers/image-definition.html
  package-lock.json
  package.json
Labels: bug

#963 Suppress additional image warning
  layouts/partials/assets/adapters/hugo.html
Labels: bug

#965 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#966 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies
