Repository gethinode/hinode, pull requests merged in 2024-02, with the labels that each got.

#743 Refine responsive icon size on cards
  exampleSite/config/_default/params.toml
  layouts/partials/assets/card.html
Labels: bug

#745 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#746 Improve flex search index
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  exampleSite/hugo_stats.json
  package-lock.json
  package.json
Labels: enhancement

#747 Fix init of card padding with zero value
  layouts/partials/assets/card.html
  package-lock.json
  package.json
Labels: bug

#748 Refine fixed navbar rendering
  assets/scss/components/_navbar.scss
  layouts/partials/assets/breadcrumb.html
Labels: enhancement

#749 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#750 Restrict max range of card groups
  data/structures/card-group.yml
Labels: bug

#751 Fix more button spacing
  layouts/partials/assets/card-group.html
  package-lock.json
  package.json
Labels: bug

#752 Drop max range requirement of card groups
  data/structures/card-group.yml
  exampleSite/hugo_stats.json
  go.mod
  go.sum
Labels: bug

#753 Allow raw content for headless pages
  config/_default/hugo.toml
  go.mod
  go.sum
  layouts/partials/assets/card-group.html
  layouts/partials/assets/card.html
  layouts/partials/assets/nav.html
  layouts/partials/head/seo.html
  package-lock.json
  package.json
Labels: bug, breaking-change

#758 Refactor optional scripts
  layouts/_default/baseof.html
  layouts/partials/footer/optional-scripts.html
  package-lock.json
  package.json
Labels: enhancement

#759 Refactor single page template
  layouts/_default/single.html
  layouts/_default/single/main.html
  layouts/_default/single/sidebar.html
Labels: enhancement

#761 Use placeholder when button title is missing
  layouts/partials/assets/button.html
Labels: enhancement

#762 Update Netlify build environment
  netlify.toml
Labels: enhancement

#765 Refactor navbar to use color themes in overlay mode
  assets/js/navbar.js
  assets/scss/components/_navbar.scss
  exampleSite/hugo_stats.json
  layouts/partials/assets/navbar.html
  package-lock.json
  package.json
Labels: enhancement

#766 Fix navbar on reload and include version data
  assets/js/navbar.js
  layouts/partials/head/head.html
Labels: bug

#770 dependabot: check for updates to GitHub actions
  .github/dependabot.yml
Labels: dependencies

#771 Support preloading of local font
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  layouts/partials/head/head.html
Labels: enhancement

#772 Improve rendering of TOC dropdown
  assets/scss/components/_toc.scss
  layouts/partials/assets/toc-dropdown.html
  layouts/partials/assets/toc.html
  package-lock.json
  package.json
Labels: enhancement

#773 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#774 Refactor download button
  layouts/_default/single/panel-toc.html
  layouts/partials/assets/download.html
  layouts/partials/assets/sharing.html
Labels: enhancement

#775 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#780 Introduce figclass attribute for images
  data/structures/image.yml
  exampleSite/hugo_stats.json
  layouts/_default/single/body.html
  layouts/partials/assets/image.html
  layouts/partials/single/thumbnail.html
  package-lock.json
  package.json
Labels: enhancement

#769 exampleSite: use go workspace pointing to local hinode clone
  exampleSite/.gitignore
  exampleSite/config/_default/hugo.toml
  exampleSite/config/postcss.config.js
  exampleSite/go.mod
  exampleSite/go.sum
  exampleSite/hinode.work
  exampleSite/hinode.work.sum
  netlify.toml
Labels: enhancement, invalid

#793 Refine icon and label spacing
  exampleSite/config/_default/params.toml
  layouts/partials/assets/navbar.html
  netlify.toml
Labels: bug

#797 Update Hugo module dependencies
  exampleSite/go.mod
  go.mod
  go.sum
Labels: dependencies

#808 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#810 Bump package release
  package-lock.json
  package.json
Labels: skip-changelog
