Repository gethinode/hinode, pull requests merged in 2024-03, with the labels that each got.

#814 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#816 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#817 Sync with main
  go.mod
  go.sum
Labels: skip-changelog

#818 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#819 Support render hook for cards
  data/structures/card-group.yml
  data/structures/card.yml
  layouts/partials/assets/card-group.html
  layouts/partials/assets/card.html
  package-lock.json
  package.json
Labels: enhancement

#827 Change missing media asset from error to warning
  layouts/partials/assets/download.html
Labels: enhancement

#828 Fix resource issue with Hugo v0.123.8
  layouts/partials/head/icons.html
  package-lock.json
  package.json
Labels: bug

#830 Enable markdown content for card body
  layouts/partials/assets/card.html
  package-lock.json
  package.json
Labels: enhancement

#835 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#836 Fix icon resource handling
  layouts/partials/head/icons.html
  package-lock.json
  package.json
Labels: bug

#837 Fix icon path
  layouts/partials/head/icons.html
Labels: bug

#838 Bump package release
  package-lock.json
  package.json
Labels: skip-changelog

#839 Finalize release v0.23.0
  netlify.toml
  package-lock.json
  package.json
Labels: dependencies

#840 Revert card body handling to HTML
  layouts/partials/assets/card.html
  package-lock.json
  package.json
Labels: bug

#841 Support custom button label on cards
  data/structures/card.yml
  layouts/partials/assets/card-group.html
  layouts/partials/assets/card.html
Labels: enhancement

#842 Update release references
  data/structures/card.yml
  data/structures/image.yml
  package-lock.json
  package.json
Labels: documentation

#843 Add missing figclass for image shortcode
  layouts/shortcodes/image.html
Labels: bug

#845 Update FR language with the latest hinode version
  exampleSite/content/fr/blog/bootstrap-elements.md
  i18n/fr.yaml
Labels: enhancement

#847 Fix section menu dropdown on small screens
  layouts/partials/assets/section-menu.html
Labels: bug

#852 Fix paginator
  layouts/partials/assets/card-group.html
  package-lock.json
  package.json
Labels: bug

#854 Fix navbar divider color in overlay mode
  assets/scss/components/_navbar.scss
  package-lock.json
  package.json
Labels: bug

#855 Fix brand logo alignment on small screens
  layouts/partials/assets/navbar.html
Labels: bug

#864 Add base theme placeholder
  assets/scss/app-dart.scss
  assets/scss/app.scss
  assets/scss/theme/base.scss
Labels: enhancement

#865 Bump package release
  package-lock.json
  package.json
Labels: skip-changelog

#866 Fix alignment of card buttons
  exampleSite/hugo_stats.json
  layouts/partials/assets/card.html
  package-lock.json
  package.json
Labels: bug
