Repository gethinode/hinode, pull requests merged in 2024-10, with the labels that each got.

#1225 Support configurable CSP directives
  .gitignore
  config/_default/hugo.toml
  config/_default/params.toml
  config/_default/server.toml
  data/netlify.toml
  data/server.toml
  exampleSite/config/_default/hugo.toml
  exampleSite/config/_default/server.toml
  exampleSite/hugo_stats.json
  go.mod
  go.sum
  netlify.toml
  package-lock.json
  package.json
Labels: release-highlight

#1229 Fix responsive behavior of card group
  data/server.toml
  layouts/partials/assets/card-group.html
Labels: bug

#1230 Refine CSP configuration
  config/_default/hugo.toml
  config/_default/params.toml
  exampleSite/hugo_stats.json
  package-lock.json
  package.json
Labels: documentation

#1236 Shift custom 404 redirects to data file
  exampleSite/config/_default/server.toml
  exampleSite/data/server.toml
  netlify.toml
Labels: bug

#1233 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#1237 Modify hugo mod update
  exampleSite/go.mod
  exampleSite/go.sum
  exampleSite/hugo_stats.json
  go.mod
  go.sum
  package.json
Labels: bug

#1238 Modify server headers
  config/_default/server.toml
  exampleSite/config/_default/netlify.toml
  exampleSite/config/_default/server.toml
  exampleSite/data/server.toml
  exampleSite/hugo_stats.json
  hugo_stats.json
  netlify.toml
Labels: bug

#1239 Bump package release
  package-lock.json
  package.json
Labels: skip-changelog

#1244 Support configuration of internal links validation
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  layouts/partials/assets/card.html
  package-lock.json
  package.json
Labels: enhancement

#1246 Support meta.robots attribute in page params
  layouts/partials/head/seo.html
Labels: enhancement

#1247 Fix sharing button
  hugo_stats.json
  layouts/partials/assets/sharing.html
Labels: bug

#1248 Fix navbar color mode update
  assets/js/navbar.js
Labels: bug

#1250 Fix add module code
  layouts/partials/utilities/AddModule.html
Labels: bug

#1251 Assign theme color and site language to essential cookie category
  assets/js/critical/_cookie.js
  assets/js/critical/color.js
  assets/js/critical/languageSelector.js
  eslint.config.js
Labels: bug

#1252 Update Hugo module dependencies
  exampleSite/go.mod
  exampleSite/go.sum
  go.mod
  go.sum
Labels: dependencies

#1253 Bump package release
  package-lock.json
  package.json
Labels: skip-changelog

#1257 Fix link to multilingual page resources
  layouts/partials/assets/link.html
  layouts/shortcodes/link.html
  package-lock.json
  package.json
Labels: bug

#1259 Support multiple sharing buttons on same page
  assets/js/sharing.js
  layouts/partials/assets/sharing.html
Labels: bug

#1261 Improve deployment to subfolder
  assets/js/critical/languageSelector.js
  exampleSite/hugo_stats.json
  go.mod
  go.sum
  layouts/partials/assets/link.html
Labels: bug

#1263 Improve SEO score of navbar item without url
  layouts/partials/assets/navbar-item.html
  package-lock.json
  package.json
Labels: bug

#1262 Fix attribute aria-inledby -> aria-labelledby
  layouts/_default/single.html
Labels: bug

#1268 Improve site accessibility and SEO score
  assets/scss/components/_nav.scss
  config/_default/params.toml
  config/_default/server.toml
  exampleSite/config/_default/params.toml
  exampleSite/config/_default/server.toml
  exampleSite/content/en/blog/bootstrap-elements.md
  exampleSite/hugo_stats.json
  go.mod
  go.sum
  hugo_stats.json
  i18n/de.yaml
  i18n/en.yaml
  i18n/fr.yaml
  i18n/nl.yaml
  layouts/partials/assets/carousel-item.html
  layouts/partials/assets/helpers/image-definition.html
  layouts/partials/assets/nav.html
  layouts/partials/assets/navbar.html
  layouts/partials/footer/scripts.html
  layouts/shortcodes/nav.html
  netlify.toml
  package-lock.json
  package.json
Labels: breaking-change

#1269 Fix link cleaning and navbar menu check
  layouts/partials/assets/link.html
  layouts/partials/assets/navbar-item.html
Labels: bug

#1270 Improve navbar modal search accessibility
  layouts/partials/assets/navbar.html
  package-lock.json
  package.json
Labels: bug

#1274 Init default card color variable
  assets/scss/common/_variables.scss
  package-lock.json
  package.json
Labels: bug

#1275 Shift Hugo highlighting options to Hinode docs
  data/structures/file.yml
  exampleSite/content/en/blog/file-highlight.md
Labels: documentation

#1276 Fix button label argument
  layouts/partials/assets/card-group.html
  package-lock.json
  package.json
Labels: bug
