Repository gethinode/hinode, pull requests merged in 2024-07, with the labels that each got.

#1018 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#1020 Add initial support for masonry layout
  assets/scss/app-dart.scss
  assets/scss/app.scss
  assets/scss/common/_masonry.scss
  package-lock.json
  package.json
Labels: enhancement

#1021 Add plain argument to navbar-item
  data/structures/navbar-item.yml
  layouts/partials/assets/navbar-item.html
Labels: enhancement

#1030 Support module dependencies
  layouts/partials/footer/optional-scripts.html
  layouts/partials/head/head.html
  layouts/partials/utilities/AddModule.html
Labels: enhancement

#1032 Add support for data tables
  assets/scss/components/_table.scss
  config/_default/hugo.toml
  data/structures/table.yml
  exampleSite/content/en/blog/components.md
  exampleSite/hugo_stats.json
  go.mod
  go.sum
  layouts/partials/assets/table.html
  layouts/shortcodes/table.html
  package-lock.json
  package.json
Labels: release-highlight

#1033 Fix dark mode of data table paginator
  assets/scss/components/_table.scss
Labels: bug

#1035 Fix table parameter initialization
  layouts/shortcodes/table.html
  package-lock.json
  package.json
Labels: bug

#1036 Fix purging of data tables styles
  config/postcss.config.js
  package-lock.json
  package.json
Labels: bug

#1038 Fix image portrait mode
  assets/scss/components/_table.scss
  exampleSite/content/en/blog/bootstrap-elements.md
  exampleSite/hugo_stats.json
  layouts/partials/assets/helpers/image-definition.html
  layouts/partials/assets/helpers/image-dimension.html
Labels: bug

#1042 Validate local url of menu entries
  layouts/partials/assets/navbar-item.html
Labels: enhancement

#1045 Suppress image container when wrapper class is empty
  layouts/partials/assets/helpers/image-definition.html
  layouts/partials/assets/navbar-item.html
  package-lock.json
  package.json
Labels: bug

#1039 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#1047 Suppress undefined navbar links
  layouts/partials/assets/navbar-item.html
  package-lock.json
  package.json
Labels: bug

#1043 Add missing params.opengraph locale for fr_FR, nl_NL
  .gitignore
  exampleSite/config/_default/languages.toml
Labels: bug

#1050 Adjust main cover style
  assets/scss/common/_styles.scss
  package-lock.json
  package.json
Labels: bug

#1052 Fix layout of scrollable card group
  layouts/partials/assets/card-group.html
Labels: bug

#1053 Fix priority of card's thumbnail and icon args
  layouts/partials/assets/card.html
Labels: bug

#1054 Adjust card title size on small screens
  exampleSite/hugo_stats.json
  layouts/partials/assets/card.html
  package-lock.json
  package.json
Labels: enhancement

#1055 Support image crop box placement
  data/structures/image-adapter.yml
  data/structures/image.yml
  exampleSite/content/en/blog/image.md
  layouts/partials/assets/adapters/cloudinary.html
  layouts/partials/assets/adapters/hugo.html
  layouts/partials/assets/adapters/imagekit.html
  layouts/partials/assets/adapters/imgix.html
  layouts/partials/assets/helpers/image-definition.html
  layouts/partials/assets/helpers/image-dimension.html
  layouts/partials/assets/helpers/image-set.html
  layouts/partials/assets/image.html
  layouts/shortcodes/image.html
  package-lock.json
  package.json
Labels: enhancement

#1056 Add anchor support to cards
  data/structures/card.yml
  layouts/partials/assets/adapters/hugo.html
  layouts/partials/assets/card-group.html
  layouts/partials/assets/card.html
  layouts/shortcodes/card.html
  package-lock.json
  package.json
Labels: enhancement

#1061 Optimize image size of scrollable card group
  layouts/partials/assets/card-group.html
Labels: enhancement

#1062 Bump package release
  package-lock.json
  package.json
Labels: skip-changelog
