Repository gethinode/hinode, pull requests merged in 2024-11, with the labels that each got.

#1292 Update Hugo module dependencies
  go.mod
  go.sum
Labels: dependencies

#1293 Add option to silence dart sass deprecation warnings
  exampleSite/config/_default/params.toml
  layouts/partials/head/stylesheet.html
  package-lock.json
  package.json
  theme.toml
Labels: enhancement

#1294 Fix French data table example
  exampleSite/content/fr/blog/components.md
  go.mod
  go.sum
Labels: bug

#1287 Params config for thumbnails.ratio
  layouts/partials/single/thumbnail.html
Labels: enhancement

#1296 Fix anchor handling of cover image
  hugo_stats.json
  layouts/partials/single/thumbnail.html
  package-lock.json
  package.json
Labels: bug

#1297 Contain aspect ratio of svg card thumbnails
  exampleSite/hugo_stats.json
  layouts/partials/assets/card.html
  package-lock.json
  package.json
Labels: bug
